CREATE TABLE REGISTERED_USERS(
USER_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
NAME VARCHAR(50) NOT NULL,
PHONE VARCHAR(10) UNIQUE
);

CREATE TABLE ROLES(
ROLE_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(50) UNIQUE
);

CREATE TABLE USER_ROLE(
USER_ID BIGINT(20),
ROLE_ID BIGINT(20),
PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE TABLE PATIENTS(
PATIENT_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
AGE INT(3) NOT NULL,
GENDER VARCHAR(1) NOT NULL,
ADDRESS VARCHAR(100),
EMAIL VARCHAR(50),
USER_ID BIGINT(20),
FOREIGN KEY FK_USER_PATIENT(USER_ID)
REFERENCES REGISTERED_USERS(USER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
----------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO roles(role_name) VALUES('ROLE_USER');
INSERT INTO roles(role_name) VALUES('ROLE_PM');
INSERT INTO roles(role_name) VALUES('ROLE_ADMIN');